### ISSUE TITLE
Tokens passed to `include` that contain an `isSource` property are treated as source files

### ISSUE THREAD

**Issue by dstaley** [amzn/style-dictionary#1007]
When passing tokens via `include` that contain the property `isSource: true`, the included tokens are indistinguishable from actual source tokens, resulting in the inability to distinguish during a `filter`.

[Reproduction](https://stackblitz.com/edit/style-dictionary-example-l5t1yn?file=config.js)

Expected result: `build/figma/figma.tokens.json` contains only the `blue-500` token since it's defined in `tokens/color.js`

Actual result: output contains tokens from both `tokens/color.js` and `include/tokens.json`

According to the [v3 migration guide](https://amzn.github.io/style-dictionary/#/version_3?id=adding-filepath-and-issource-entries-on-tokens:~:text=isSource%3A%20A%20boolean%20representing%20if%20this%20file%20was%20defined%20as%20%E2%80%98source%E2%80%99%20in%20the%20configuration%20as%20opposed%20to%20%E2%80%98include%E2%80%99%20(or%20directly%20setting%20the%20%E2%80%98properties%E2%80%99%20object).%20This%20can%20also%20help%20filtering%20tokens%20from%20output%20files%20you%20don%27t%20want%20to%20include.):

> isSource: A boolean representing if this file was defined as ‘source’ in the configuration as opposed to ‘include’ (or directly setting the ‘properties’ object). This can also help filtering tokens from output files you don't want to include.

Since the default `json` formatter includes the `isSource` property, I think it would make sense to give it special treatment when it's seen in a file coming from `include` and manually override it to `false`.

**Comment by jorenbroekema** [comment]
I'm not sure I understand why your "include" tokens source files contain design tokens that already contain the metadata props that style-dictionary is supposed to fill out for you. That said, I will file this as a bug because style-dictionary is supposed to set the isSource property itself whether it's already been prefilled or not.

I think we also need to have a discussion on how metadata properties should be handled in general.
According to the DTCG spec, you'd put it either in property names starting with `$` prefix, or you'd put it into the $extensions under the unique namespace of your tool (e.g. style-dictionary). If I'm not mistaken, $metada props are something that belong to the token authors territory, and $extensions is where tools can put their stuff, so I'm leaning towards refactoring everything to scope and read metadata from that `$extensions['com.styledictionary']` namespace

**Comment by jorenbroekema** [comment]
Closing this as in DTCG, token authors are supposed to use $ prefixes for additional token props to prevent issues like these, or if they are tool-authors they should use "$extensions" to place their meta data. Style Dictionary is different because it only parses your tokens and creates a dictionary with metadata, which doesn't have to follow DTCG format at that point any longer, since we're not outputting back to DTCG format
