### ISSUE TITLE
"javascript/es6" format vs. transformGroup "web"

### ISSUE THREAD

**Issue by didoo** [amzn/style-dictionary#108]
Looking at the documentation (which is amazing, btw!) it's not clear to me the relation between the format "javascript/es6" and the transformGroup "web". 

I have created a simple example config:
```
{
  "source": ["properties/test.json"],
  "platforms": {
    "test": {
      "transformGroup": "web",
      "buildPath": "test/js/",
      "files": [{
        "destination": "tokens.es6.js",
        "format": "javascript/es6"
      }]
    }
  }
}
```

that reads from a very simple properties file:
```
{
  "background": {
    "base": { "value": "#ffffff" },
    "alt": { "value": "#fcfcfcfc" }
  }
}
```
The problem I have is that using the _"transformGroup": "web"_ the generated file is not a valid JS/ES6 file:
```
export const background-base = '#ffffff';
export const background-alt = '#fcfcfcfc';
```
The only way I can have it working is by replacing the _transformGroup_ declaration with a custom transformation:
```
"transforms": ["attribute/cti","name/cti/constant","size/px"]
```
which results in a valid JS/ES6 file:
```
export const BACKGROUND_BASE = '#ffffff';
export const BACKGROUND_ALT = '#fcfcfcfc';
```

Looking at [the example in the documentation](https://github.com/amzn/style-dictionary/blob/f6cfa273c844899118dfea709babd3bb0a431e2a/docs/formats.md#javascriptes6) I see no transformation or _transformGroup_ is declared, but the output is actually in PascalCase, but I can obtain it only applying the custom transforms:
```
"transforms": [ ... ,"name/cti/pascal", ... ]
```

So I am not sure if somehow I am missing something, or actually is an expected behaviour (in that case probably better to update the documentation and be more explicit).

**Comment by dbanksdesign** [comment]
You aren't missing anything, I think this is just some mis-matched code. The "web" transform group applies the transforms: attribute/cti, name/cti/kebab, size/px, and color/css. As you pointed out, the "name/cti/kebab" transform creates the name "background-base", which is not a valid variable name in Javascript. 

To your original question about how the "web" transformGroup relates to the "javascript/es6" format is that they are 2 steps in the build process. All the transforms, defined by a transformGroup or by an array of transforms, get applied to all the style properties. Transforms can either modify the value (like hex to rgb), the name (like BACKGROUND_BASE), or arbitrary attributes that can be used later. After the transforms are applied, the transformed style dictionary object is passed to the format which uses the names/values of the properties to output a file. 

This does bring up an issue that we should define a "js" transform group that uses valid names and values so they don't break using it in formats like "javascript/es6". The name "web" for the transformGroup is probably misleading as well, because really it can only be used for CSS/Sass files. 

You also bring up a good point about the documentation, that example was a careless mistake by leaving out lines of code in the example to make it work. 

Let me know if that all makes sense. I will try to cut a PR tonight adding a "js" transformGroup and fix the documentation you pointed out.

**Comment by didoo** [comment]
Just a couple of comments:

> _The name "web" for the transformGroup is probably misleading as well, because really it can only be used for CSS/Sass files._ 

100% agree :)

> All the transforms, defined by a transformGroup or by an array of transforms

Yesterday I tried to apply the _transforms/transformGroup_ properties directly inside the _files_ item like this:
```
{
  "source": ["properties/test.json"],
  "platforms": {
    "test": {
       "transformGroup": "web",
      "buildPath": "test/js/",
      "files": [{
        "transformGroup": "custom", // these would be mutually exclusive
        "transforms": ["attribute/cti","name/cti/constant","size/px"], // these would be mutually exclusive
        "destination": "tokens.es6.js",
        "format": "javascript/es6"
      }]
    }
  }
}
```
do you think this could be a "pattern" to declare specific props that would override the _platform_ declaration? or it would over-complicate things without a real benefit? keep in mind that I love how the APIs have been designed, so simple and clear that even a non-JS developer like me could pick up the project and create a custom build in one day! So, I am not suggest to change anything, I am just sharing something that may be useful in the future.

Thank you for your time, and your PR!

**Comment by dbanksdesign** [comment]
That is an interesting point about putting transforms/transformGroups inside file declarations. I think having that makes sense in the case where each file you want to generate needs it's own transforms/transformGroup. This makes sense for web things like having a JS file and a CSS file. Having transforms/transformGroups at the platform level makes more sense for things like Android and iOS where you will probably be generating multiple files and won't need to have different transforms for each file within the platform. That is what I had in my when I first built transforms/formats. 

What you are trying to do, in reality, is possible although not exactly the same way. You could, put a single file in each platform and define the transforms/transformGroup at each platform. If you end up mixing and matching transforms like using the same 3 transforms across a few files/platforms, it might help to use the node module rather than the CLI. With that you can write plain javascript to build your config and concat arrays of transforms as necessary. In this example the config is a plain JS object: https://amzn.github.io/style-dictionary/#/quick_start?id=node

Here is a rough example of that (this code is untested, but *should* work):
```js
const baseTransforms = ["attribute/cti", "size/px"];
const jsTransforms = baseTransforms.concat(["name/cti/pascal"]);
const scssTransforms  = baseTransforms.concat(["name/cti/kebab"]);

const StyleDictionary = require('style-dictionary').extend({
  source: ['properties/**/*.json'],
  platforms: {
    scss: {
      transforms: scssTransforms,
      buildPath: 'build/scss/',
      files: [{
        destination: 'variables.scss',
        format: 'scss/variables'
      }]
    },
    js: {
      transforms: jsTransforms,
      buildPath: 'build/js/',
      files: [{
        destination: 'styleDictionary.js'
        format: 'javascript/es6'
      }]
    }
    // ...
  }
});

StyleDictionary.buildAllPlatforms();
```

We have been having some discussions around larger architectural themes relating to the build process and how style dictionary does transforms, reference replacements, then writes files. Some things that have come from those discussions is the loose distinction between what goes into transforms versus what goes into formats/templates. *Technically* if you wanted to, you could use no transforms and write custom formats that handle all the transforming of the data yourself... 

Does that all make sense/did I answer your question?

**Comment by chazzmoney** [comment]
I think this has been fully handled, feel free to re-open if needed.
