### ISSUE TITLE
zsh: command not found: style-dictionary

### ISSUE THREAD

**Issue by darkovski88** [amzn/style-dictionary#1098]
First of all, I wanted to point out that im new to this, and thanks for providing such a tool, and thanks for understanding the "minor" issue that im facing with. 
**Issue:** After following the [this guide](https://amzn.github.io/style-dictionary/#/quick_start), and try to run `style-dictionary init basic` in my CLI(using MacOS terminal) - im facing with this issue:
`zsh: command not found: style-dictionary`

How I end up here is that I open the terminal, navigate to the desired folder and execute the `style-dictionary init basic` command. Is this the proper way to initialise and run style-dictionary?

Can anyone please help out on what can the issue be? I do have node version v20.11.0 and npm installed. Any hints would be greatly appreciated. 

Thanks

**Comment by quasters** [comment]
same problem =(

**Comment by jorenbroekema** [comment]
You can also install style-dictionary locally and proceed to use it with `npx` (part of  `npm`, it uses your local installation of the binary and if it does not exist, temporarily installs it for you after giving you a prompt for permission)

```bash
npm i style-dictionary
npx style-dictionary init basic
```

If you want it globally you'll have to make sure of two things:
- Install style-dictionary globally (`npm i -g style-dictionary`)
- Ensure your PATH variable contains the global node_modules/.bin folder so that it can find `style-dictionary` command. This will be slightly different depending on whether you use bash, zsh, whatever
