### ISSUE TITLE
How to access FormatterArguments types, etc.

### ISSUE THREAD

**Issue by lukasoppermann** [amzn/style-dictionary#1135]
Hey @jorenbroekema,

I have no idea how to access some types, like `FormatterArguments`.

They are not exported from `style-dictionary/types` and also not available through something like `Format['FormatterArguments']`.

The way you use it in here, seems to not be typical typescript, so can you help me find out how I can access those types? Thanks.

One of the places where I have this issue is here: https://github.com/lukasoppermann/style-dictionary-utils/pull/65/files#diff-4c8b203eb592cb0973b6227b4be99616520e7b0351981b54dfbd320fd0aa117aR3

**Comment by jorenbroekema** [comment]
Hmm I think I should consider exporting all types inside our types directory instead of only the main interfaces.

PRs very welcome to adjust https://github.com/amzn/style-dictionary/blob/v4/types/index.d.ts and export all from all sibling .d.ts files (Volume.d.ts is new, should be added as well)

**Comment by lukasoppermann** [comment]
Somehow for me using this "trick" I don't get ts autocomplete or suggestions.

**Comment by lukasoppermann** [comment]
PR is up: https://github.com/amzn/style-dictionary/pull/1137

Hope this is what you meant.

**Comment by jorenbroekema** [comment]
Works for me. Since style-dictionary uses package entrypoints your tsconfig compilerOptions needs `"module": "nodenext"` and  `"moduleResolution": "nodenext"` or `"moduleResolution": "bundler"` if you need it e.g. extensionless imports, otherwise it won't be able to find the declarations

![image](https://github.com/amzn/style-dictionary/assets/36734656/a6287899-f51f-4757-a0bc-6330f7ca52b1)
