### ISSUE TITLE
resolveObject - circular definition error if more than 2 references in a value?

### ISSUE THREAD

**Issue by didoo** [amzn/style-dictionary#118]
I don't know if this is an error or an expected behavior. 

Let's consider these declarations:

```
{
  "prop1" : { "value": "test1 value" },
  "prop2" : { "value": "test2 value" },
  "prop3" : { "value": "test3 value" }
}
```

When I reference two property values (as aliases) in another property the compilation works as expected. 
This:
```
"prop123" : { "value": "{prop1.value}, {prop2.value} and some extra stuff" }
```
generates in output this (eg. CSS variables):
```
--prop-123: test1 value, test2 value and some extra stuff;
```

But when I reference three property values (as aliases) the compilation throws an error.
This:
```
"prop123" : { "value": "{prop1.value}, {prop2.value} and {prop3.value}" }
```
generates this error:
<img width="1206" alt="screenshot_1682" src="https://user-images.githubusercontent.com/686239/44462970-7eb3bd00-a616-11e8-8f88-38bae6fd5f0c.png">

Oddly enough, this happens also if I do something similar, using two aliases but referencing the same prop:
```
"prop22" : { "value": "{prop2value}, {prop2.value}" }
```
throws the same kind of error.

I looked in the code for the [resolveObject](https://github.com/amzn/style-dictionary/blob/master/lib/utils/resolveObject.js) method, but I am not sure where the culprit is.

Is this an issue, or actually is some kind of safeguard in place to avoid too many recurrences?

**Comment by didoo** [comment]
Mmm, I have also noticed this thing: the error message string says:
```
Error: Variable reference for 'value' resolves to circular definition cycle of 'est1 value test2 value and {prop3.value':
```

If you notice the beginning and end of the string are missing the initial and final characters (_'est1'_ and  '_{prop3.value'_) so maybe is in the way the regexes are executed? in the resolveObject file I see this:

```
 regex = new RegExp(
    '\\' +
    options.opening_character +
    '([^' +
    options.closing_character +
    ']+)' +
    '\\' +
    options.closing_character, 'g'
  );
```
so maybe is considering the whole multiple aliases as a single declaration (but then, why it works with two?)

**Comment by dbanksdesign** [comment]
I think I know what is going on here, we recently made a change to have better error messages like collect all circular definitions and all reference not found so that you can see all the issues rather than seeing one, fixing it, re-building, repeating. I'm pretty sure the offending line is this one:
https://github.com/amzn/style-dictionary/blob/master/lib/utils/resolveObject.js#L88

For the circular reference check, a few lines above we are creating an array of resolved strings that it checks against. The reason the first one works but the other 2 examples do not is that the first one has extra text after the references I think... 

While looking in to this, I'm also debating whether string interpolation in values is a good thing. I originally wrote it that way to do stuff like border short-hand: "{size.border.width.base} solid {color.border.base}", but I now realize that is platform-specific syntax and would not work for anything other than CSS....

**Comment by didoo** [comment]
> The reason the first one works but the other 2 examples do not is that the first one has extra text after the references I think...

No, it works also without the extra string after.
This:
```
"prop12" : { "value": "{prop1.value} {prop2.value}" },
```
generates this (Sass variable):
```
$token-prop-22: test1 value test2 value;
```
¯\_(ツ)_/¯

Regarding if the string interpolation is a good thing or not, personally I've found it useful (and in general it allows a certain flexibility, people can declare token values as composition of other token values) but I understand that it may add extra complexity to the object resolver.

No strong opinions here, I'll leave it to you.
