### ISSUE TITLE
Combining Color and Density Modes

### ISSUE THREAD

**Issue by kentonquatman** [amzn/style-dictionary#1214]
I'm currently using Style Dictionary to support light and dark modes in a component library. I'm interested in adding support for default and compact spacing modes. Is this possible with a single instance of Style Dictionary? They could be combined into a single sheet (eg. dark-compact.css) or two separate files (eg. color-dark.css + space-compact.css).

**Comment by jorenbroekema** [comment]
I've found it to be quite challenging to do this inside a single StyleDictionary instance because if you give a token multiple values (one for each theme), it'll likely not run the transforms on all of them properly.

My recommendation is to have 3 layers of tokens:
- your primitives, think of a color palette, spacer scale etc. thing that are not theme dependent and not semantic
- your semantic layer, think of "color primary", "color accent", tokens that have some semantic meaning and that can change depending on the current theme, e.g. foreground color primary may be light blue on dark mode and dark blue on light mode
- your component layer, things that consume from the semantic tokens, e.g. button background color -> consumes background color primary (changes depending on theme) -> consumes blue 500 from the palette

Then when you run style dictionary, you create a separate instance for each theme permutation e.g. light compact, which has for example the following source:
```
{
  "sources": [
    "core.json",
    "semantic.json", // semantics but those that dont change by theme
    "light.json", // semantic tokens that have light-theme specific overrides
    "compact.json", // semantic tokens that have ciompact-theme specific overrides
    // comp tokens
    "button.json",
    "accordion.json",
  ]
}
```
And then for let's say spacious dark mode you can swap out `light.json` and `compact.json` with `dark.json` and `spacious.json`, they have the same token definitions, just different values (references to different primitives)

Then in the files/output make sure to use theme-specific filenames or output folders so you're not overwriting the same files.

This approach has been somewhat documented in https://github.com/tokens-studio/lion-example (demo: https://lion-example.netlify.app/), it's a little bit specific to Tokens Studio because of the fact that that plugin creates a `$themes.json` file with the themes information, but you can quite easily reuse the same concepts and not need Tokens Studio.

There's also this example in this repo https://github.com/amzn/style-dictionary/tree/v4/examples/advanced/multi-brand-multi-platform which follows roughly the same approach.

The main reason for me recommending to handle theming 1 abstraction layer above the tokens layer (and thus having multiple SD instances) is because it's scalable. Trying to jam all possible theme values inside the tokens themselves isn't scalable, which you notice fairly quickly once you introduce multiple dimensions of theming.

**Comment by kentonquatman** [comment]
Thanks! I just realized I can do what I need using the same approach as the multi-brand-multi-platform example.
