### ISSUE TITLE
4.0 prerelease includes packages with unclear licensing

### ISSUE THREAD

**Issue by sfc-gh-dmajumdar** [amzn/style-dictionary#1250]
Style-dictionary as of 4.0.0-prerelease.37 contains dependencies that fail snyk security checks due to missing licensing information

Here are the 2 dependencies that seem to have either missing or non-compliant licenses 

* style-dictionary@4.0.0-prerelease.37 › @bundled-es-modules/memfs@4.8.1 › memfs@4.9.3 › tree-dump@1.0.1 
* style-dictionary@4.0.0-prerelease.37 › @bundled-es-modules/glob@10.3.13 › stream@0.0.2 › emitter-component@1.1.2

**Comment by jorenbroekema** [comment]
https://github.com/streamich/tree-dump/blob/master/LICENSE 
https://github.com/sindresorhus/component-emitter/blob/main/LICENSE

In order to fix the automatic check:
- tree-dump would need to publish the license type in package.json on NPM, rather than only having it in the github repo
- stream needs to update its dependency to the renamed "component-emitter" which does have a license in package.json on NPM

I can't really influence this as they are third party dependencies, there isn't really a memfs alternative that I can see whereas for glob I might be able to look into using https://github.com/thecodrr/fdir instead of using glob..

But hopefully you can circumvent the automatic snyk check and mark those unclear licensing cases with the links I provided above, because they are in fact licensed

**Comment by jorenbroekema** [comment]
I also opened an issue on the stream repository, and a PR on the tree-dump repository. Let's give it some time.

**Comment by dbanksdesign** [comment]
@jorenbroekema can you take a look at this?

**Comment by sfc-gh-dmajumdar** [comment]
Looks like the tree-dump issue is now resolved with 4.0.0-prerelease.38.

Stream also released a 0.0.3 with a fix
https://github.com/juliangruber/stream/commit/b4589915137c5969effd85c66b40aea2a62aed7f

are you a maintainer on `@bundled-es-modules/glob` ? to pull that in?

**Comment by jorenbroekema** [comment]
Yeah I was involved in the stream update, I maintain the esm fork of glob yeah, it's on my list to bump that and get this resolved soon 👍🏻

**Comment by jorenbroekema** [comment]
Released in .39

**Comment by sfc-gh-dmajumdar** [comment]
Still seeing this issue on .39
```
style-dictionary@4.0.0-prerelease.39 › @bundled-es-modules/memfs@4.8.1 › stream@0.0.2 › emitter-component@1.1.2 
```

**Comment by jorenbroekema** [comment]
Ah true, I didn't remember that the memfs ESM fork also uses stream shim for browser compat. Will have to bump it there and release a new version, then bump it in style-dictionary and release as a new patch.
