### ISSUE TITLE
transitive transforms example v4: cannot read properties of undefined

### ISSUE THREAD

**Issue by woylie** [amzn/style-dictionary#1259]
I updated Style Dictionary to 4.0.0 and also updated a transitive transform to follow the updated example:

https://github.com/amzn/style-dictionary/blob/main/examples/advanced/transitive-transforms/sd.config.js

I copied the example without modifications. However, I'm getting the error:

```
"color/css": Object.assign({}, StyleDictionary.transform[`color/css`], {
                                                          ^
TypeError: Cannot read properties of undefined (reading 'color/css')
```

What am I missing?

**Comment by jorenbroekema** [comment]
Yep I missed this instance during the refactor to `.hooks`.

It should be `StyleDictionary.hooks.transforms['color/css']`.

**Comment by woylie** [comment]
Nice, that fixes this issue. However, I'm getting a different error with the same example now:

```
Unknown transform "colorTransform" found in platform "css":
"colorTransform" does not match the name of a registered transform.
```

**Comment by jorenbroekema** [comment]
It looks like I need to update that example anyway because chroma-js is CommonJS only and it's better to use something like colorjs.io which publishes ES Modules. The reason it cannot find colorTransform is because it has to be on the config like so:
```js
export default {
  hooks: {
    transforms: {
      colorTransform: {
        type: `value`,
        // only transforms that have transitive: true will be applied to tokens
        // that alias/reference other tokens
        transitive: true,
        filter: (token) => token.attributes.category === 'color' && token.modify,
        transform: colorTransform,
      }
    }
  }
}
```

Then migrating away from chroma-js and it should work. But I'll keep this issue open until I've checked the examples again and ensure the work.
