### ISSUE TITLE
ReferenceError: TransformStream is not defined

### ISSUE THREAD

**Issue by Dannom** [amzn/style-dictionary#1304]
Hey, 
Ive been trying to use the build cli command but keep getting this error: 

/ILPETDAOM/AppData/Roaming/nvm/v14.15.5/node_modules/style-dictionary/node_modules/@zip.js/zip.js/lib/core/streams/crc32-stream.js:33
class Crc32Stream extends TransformStream {
                          ^

ReferenceError: TransformStream is not defined
    at file:///C:/Users/ILPETDAOM/AppData/Roaming/nvm/v14.15.5/node_modules/style-dictionary/node_modules/@zip.js/zip.js/lib/core/streams/crc32-stream.js:33:27
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

has anyone ever faced this? 
thanks

**Comment by adamstankiewicz** [comment]
I believe this is likely due to running `style-dictionary` with an older, unsupported version of Node. 

Note the `main` branch defines the minimum supported Node version as >=18.0.0 ([source](https://github.com/amzn/style-dictionary/blob/ed64beec9a1fffa5c6df5a89ab0e70123e1eca13/package.json#L34-L36)), but per your error trace output above, it appears you're running Node v14 via `nvm` (Node Version Manager).

Try doing `node -v` to output your current Node version to verify. The fix would be to try switching to Node 18+ (e.g., `nvm use 18`).

**Comment by jorenbroekema** [comment]
Closing question issue, considered as answered. Node minimal version is now in migration docs as well as pkg json engines field
