### ISSUE TITLE
`sortByReference` inverted (and incorrect) when using DTCG standard

### ISSUE THREAD

**Issue by chris-dura** [amzn/style-dictionary#1305]
```javascript
// config.mjs

{
  "platforms": {
    "css": {
      "transformGroup": "css",
      "files": [
        {
          "destination": "vars.scss",
          "format": "scss/variables",
          "options": {
              "outputReferences": true
          }
        }
      ]
    }
  }
}
```

v3 format:

```json
{
  "colors": {
    "red": {
      "value": "#ff0000",
      "type": "color"
    },
    "primary": {
      "value": "{colors.red}",
      "type": "color"
    }
  }
}
```

Expected output, `$colors-red` is referenced after it is declared:

```scss
// Do not edit directly, this file was auto-generated.

$colors-red: #ff0000;
$colors-primary: $colors-red;
```

Change to DTCG format:

```json
{
  "colors": {
    "red": {
      "$value": "#ff0000",
      "$type": "color"
    },
    "primary": {
      "$value": "{colors.red}",
      "$type": "color"
    }
  }
}
```

Incorrect output, `$colors-red` is referenced before it is declared.

```scss
// tokens.scss output

// Do not edit directly, this file was auto-generated.

$colors-primary: $colors-red;
$colors-red: #ff0000;
```

**Comment by jorenbroekema** [comment]
Oof that's not good, definitely seems like a bug, will take a look

**Comment by lukasoppermann** [comment]
Hey, any news here? I may be running into the same issue.

Also this example suggest to use `dictionary`, but the type needs `TransformedTokens` so `dictionary.tokens`: https://github.com/amzn/style-dictionary/blob/main/examples/advanced/format-helpers/sd.config.js#L38

**Comment by lukasoppermann** [comment]
@jorenbroekema do we just need to make sure to use `$value` if `usesDtcg` is `true` in link https://github.com/amzn/style-dictionary/blob/0cf8102afe49f51ba9e2b30e950a6fbc2dc11027/lib/common/formatHelpers/sortByReference.js#L57 and lines 59, 60, 64?

But it seems like the function does not have access to the `Config` object atm, right?

**Comment by jorenbroekema** [comment]
@lukasoppermann yeah that definitely needs to use `original.$value` if `usesDtcg` is `true`.

We should add the `usesDtcg` boolean prop to the options parameter (currently only has `unfilteredTokens` prop), and ensure that internally in Style Dictionary this sortByReference utility is called passing this option. As far as I know it is called from the format lifecycle where we do have the Config available.

PR welcome!

**Comment by timges** [comment]
Unfortunately ran into the same issue 😢. I submitted a PR that should fix it **for now** 🫡

@jorenbroekema that being said, I feel like it might be considerable refactoring the way the usesDtcg option is used across the codebase in a whole. Right now, it's repeated a lot througout the codebase like:

```js
usesDtcg ? '$value' : 'value'
// or
usesDtcg ? '$type' : 'type'
```
It actually appears to be **only** used this way.

There are small inconsistencies in how it's written exactly, which makes it a bit harder to track. I was thinking a utility function could help standardize this. 
Another thought was to actually remove the `usesDtcg` option in the first place and just fall back to `$value` when `value` is `undefined`. Could already seal the deal, couldn't it?

I'm fairly new to the codebase, and didn't have tooooo much time to browse through everything, so I might be missing things here! Would love to get your feedback though 😊

**Comment by timges** [comment]
100% agree with you @jorenbroekema! Thanks for the feedback 🙏

I'd definitely go for a full switch from the current standard to DTCG  syntax at some point. As you mentioned, since it's a breaking change anyway, it might be best to just drop support for the old standard with v5.

Test situation is a little concerning, tbh. The only other integration test suite that covers DTCG syntax seems to be `w3c-forward-compat.test.js`.

Perhaps we could eliminate the `usesDtcg` option without introducing breaking changes by always trying to access a value using the DTCG syntax first, and if it's undefined, falling back to the standard syntax. Also hacky, but at least test coverage would implicitly be guaranteed this way.

**Comment by jorenbroekema** [comment]
> Test situation is a little concerning, tbh. The only other integration test suite that covers DTCG syntax seems to be w3c-forward-compat.test.js.

Actually there are a couple of other places where we also have a test that's for DTCG syntax but you'd have to search for them to find them in the regular test files.

> trying to access a value using the DTCG syntax first, and if it's undefined, falling back to the standard syntax

I'm pretty sure that's what I went with the first time I tried to add forward compatibility with DTCG syntax but there were some issues with this approach, I don't remember exactly from the top of my head but it was something along the lines of:
- there can be token groups with name "value" in DTCG syntax, so if we use `$value ?? value` we might get a false-positive hit for a "token" when it's really just a token group. I know this to be a real world use-case for people, because they raised an issue for this when I used trial & error + fallback method for checking `$prop ?? prop`
- people were using mixed forms of old syntax and new syntax, by introducing auto-detection and introducing usesDtcg as a boolean flag, I've essentially explicitly said we don't support that (it introduces a whole can of worms on its own trying to deal with mixed format)
 
I'm not sure if it would improve test coverage either because the main reason we have these minor bugs when not taking account DTCG format is because we access `token.value` or `token.original.value` somehow and we forgot to check for `$value`, whether we do so by trial and error + fallback approach or by checking the usesDtcg option doesn't seem that relevant for test coverage I think, you'd only get the coverage if you were always checking your tests with both old syntax JSON inputs and DTCG syntax JSON inputs and for most tests we just don't.

**Comment by timges** [comment]
> there can be token groups with name "value" in DTCG syntax, so if we use $value ?? value we might get a false-positive hit for a "token" when it's really just a token group. I know this to be a real world use-case for people, because they raised an issue for this in one of the prereleases when I used trial & error + fallback method for checking $prop ?? prop
people were using mixed forms of old syntax and new syntax, by introducing auto-detection and introducing usesDtcg as a boolean flag, I've essentially explicitly said we don't support that (it introduces a whole can of worms on its own trying to deal with mixed format)

That makes a lot of sense! Dang it. Guess we reallly have to wait for v5 then, to properly improve here.

Anyways -  thanks for the awesome exchange! 😊
