### ISSUE TITLE
file not created error

### ISSUE THREAD

**Issue by karimemad09** [amzn/style-dictionary#1306]
Hello
It's my first time trying a style dictionary after exporting my JSON file from the Figma design token plugin. When I try to build it, I get this error.
Well, where is the problem right now? Also, do you recommend any export plugin to export Figma variables and work excellently with Style Dictionary?

![Screenshot 2024-08-15 145836](https://github.com/user-attachments/assets/79eec321-5f3b-4523-bc77-50f3a4b86ff0)

**Comment by soundharsaminathan** [comment]
maybe directory is not mapped correctly in config. Update the issue with your config & file structure.

**Comment by karimemad09** [comment]
> maybe directory is not mapped correctly in config. Update the issue with your config & file structure.

I thought that either, so how can I map it correctly? also, are there any blog talks about how I can build the file structure to match the default config file?

**Comment by jorenbroekema** [comment]
So this warning occurs either because:
- your "source" property in your SD config is not matching the files, so you have no tokens to process
- in the format config you have applied filters and they're filtering all the tokens out, so there's no more tokens to output to the file because the array of tokens is empty.

It's not clear from your issue which of the two it is because you haven't posted your SD config file and we don't know what your filesystem looks like, where the tokens files are located relative to where you are running SD
