### ISSUE TITLE
Unable to install and build properly

### ISSUE THREAD

**Issue by soundharsaminathan** [amzn/style-dictionary#1307]
![image](https://github.com/user-attachments/assets/a708eda9-2078-4e9e-bb8e-78a9be399384)
![image](https://github.com/user-attachments/assets/065b46c7-b600-4070-ab42-442c8519b193)

**Comment by jorenbroekema** [comment]
Hm this may be a bug where the copy_assets action is trying to copy a folder target to folder destination, and copyFile may be expecting files rather than folders.

Can you go into your node_modules/style-dictionary/lib/common/actions.js and on Line 81 change it to:

```js
return vol.promises.cp('assets', config.buildPath + 'assets');
```

so using `cp` instead of `copyFile`?

Let me know if that solves your issue

**Comment by forgantini** [comment]
<img width="772" alt="Screenshot 2024-09-02 alle 12 20 50" src="https://github.com/user-attachments/assets/32f09581-b41d-4acd-95cd-f70ed9da7019">
Hello everybody.. i've a similar issue. I've tried to change the method as described above but other (and i suppose related issues appears on unlink).

**Comment by forgantini** [comment]
<img width="594" alt="Screenshot 2024-09-02 alle 14 10 25" src="https://github.com/user-attachments/assets/b15dbcb7-f31b-4446-a7cb-fe107bac8fdd">
but there is still an issue on the unlink if you call the cleanAllPlatforms method

**Comment by jorenbroekema** [comment]
I created a PR here https://github.com/amzn/style-dictionary/pull/1329 to fix it
