### ISSUE TITLE
What is the best way to merge local design tokens with ones stored on server.

### ISSUE THREAD

**Issue by mkeyy0** [amzn/style-dictionary#1400]
We have some kind of structure where we store some tokens on the server. To make a long story short we have:
- global_tokens
- brand_tokens

Global tokens are just references to the brand_tokens. But in our case, we have many brands and can't store them just in the repo, so we store them on the server.

What is the best way to handle this case with a style dictionary? How should I combine these 2 states in the repo and on a server? Should I create a temp folder and move tokens there, or maybe the style dictionary has some API to simplify it? I would appreciate any advice

**Comment by jorenbroekema** [comment]
There's two types of input that Style Dictionary supports:
- your tokens in the form of files on the filesystem (JSON, JS, or custom file extension through custom parser API)
- tokens as a JavaScript object, passing it directly

For the first example, I suppose you would have to write an adapter that gets the tokens from the server through network calls and then mirror them to the local filesystem, this can be the "real" filesystem but you could also create an in-memory volume using something like `memfs` (or its `@bundled-es-modules/memfs` fork if you need it in prebundled ESM format) -> https://github.com/streamich/memfs/blob/master/docs/node/usage.md , that way you don't need to bother with having to persist the tokens to the filesystem which might make it easier to use in some environments (e.g. web browsers). This is a bit advanced so maybe not recommended unless you have a very specific use case like a browser playground env or isolating your integration tests so they can run in parallel (since they no longer are accessing the same filesystem). 

The second example is probably most straightforward, you get the tokens from the server and use:
```js
const sd = new StyleDictionary({
  // assuming a JSON string response from server that you already parsed as an object (e.g. `Response.json()`)
  tokens: tokensFromServer, 
  platforms: { ... } 
});
```

**Comment by mkeyy0** [comment]
Thank you for the answer!
Yeah, the one with the file system is the most suitable for me. I still want to keep tokens that are stored in the repo in JSON format, and tokens from the server just to override these tokens. Maybe I'll just create a temp folder with server tokens and pass it to the style dictionary config. Probably it's a way to go. There's no need to create an in-memory fs as this job will be executed via GH actions
