### ISSUE TITLE
Add iOS Swift format

### ISSUE THREAD

**Issue by chazzmoney** [amzn/style-dictionary#161]
This format should output a file usable in Swift that maintains the structure of the style dictionary properties. 

You can have a look at how [the current iOS formatters](https://github.com/amzn/style-dictionary/blob/54bea77a770fc43f6afffb4942dfa3a78a0c4230/lib/common/formats.js#L377) are implemented using [lodash templates](https://github.com/amzn/style-dictionary/tree/remove-templates/lib/common/templates/ios) to see how to write a formatter and where it should go.

Make sure to include proper jsdoc comments and unit test!

**Comment by davixyz** [comment]
@chazzmoney 
I kinda want to do this one, but I feel it's going to be a LOT; This could be separated to add output of usable files by different types like:
- Colors
- Strings
- Numbers
- Etc

At the same time, I'm a little bit unsure on how to produce the formats in a generic way since there's so many ways to do this! We are doing something like this where I work, but the outputs we generate are really tailored to our needs, for example: 

We are making an extension of the `UIColor` like this:
https://medium.com/ios-os-x-development/ios-extend-uicolor-with-custom-colors-93366ae148e6#6350

Without the nested structs and then you get to do something like `UIColor.something.blue` but again, some people might not like this approach. Any ideas?

**Comment by dbanksdesign** [comment]
I like having a specific one for colors where you extend UIColor, for the others we could do a generic static class that just has attributes that reference the value because you can just use a simple string or number.

**Comment by chazzmoney** [comment]
I'm not an experienced Swift developer, so I would defer to what someone who uses Swift regularly would say.

That said, I think it makes sense to output the styles in the format those styles are expected to be used in. For example, the UIColor makes sense because thats how you would use the color. There might be something similar for font sizes, etc. I just don't know enough about Swift to say for sure.
