### ISSUE TITLE
Convert config argument in format functions

### ISSUE THREAD

**Issue by chazzmoney** [amzn/style-dictionary#20]
Set the config argument to be the current file object key/value pairs (out of the files array) flattened with the platform level key/value pairs.

**Comment by dbanksdesign** [comment]
Poking around the code, we actually can get the current file object in a format. It might not be the best solution, but `this` is bound to the file object in the formatter method when it is called. This is the same for both formats and templates. So in a format method you can call `this.foo` if the file object defined in the config is 
```
{
  "destination": "foo.txt",
  "format": "someFormat",
  "foo": "bar"
}
```

Open question, what is the best way to do this? 
- Binding `this` to the file object
- Should we add a third argument to format/template methods for the file object. Now looking at it, this would not work for templates. Lodash templates take only 1 argument, so everything else is ignored. Looks like right now templates cannot access the `platform` object... but I guess that hasn't been a problem yet. 
- Change the arguments to be one object like ```{file: {}, platform: {}, dictionary: {}}``` (my vote is for this). This will introduce a breaking change though.

**Comment by chazzmoney** [comment]
We should revisit this. I don't even remember the "why" of this issue anymore. My second message makes it sounds like it was for filters inside of formats, which @elliotdickison has now redone the architecture for.

I guess I can still see the future value in extensibility by potentially converting away from a multiple argument signature to a single argument signature, but thats the main difference I see.  Thoughts?

@dbanksdesign Do you remember what this was about?  Anything I'm missing here?

**Comment by dbanksdesign** [comment]
The "why" of this originally was that we thought formats did not have access to the file object calling the format. Both formats and templates have access to the file object through `this` as in my example above. I posed the question whether this was the right architecture. I think the question still remains after @elliotdickison's filter change because there are other cases we need to pass arbitrary data to the format/template. One example is for generating iOS classes we might want to pass a className to the format/template like so:
```
{
  "destination": "MyClass.h",
  "template": "ios/Static.h.template",
  "className": "MyClass"
}
```

**Comment by chazzmoney** [comment]
Closing this until there is something that requires this functionality. We can open an issue at that point.
