### ISSUE TITLE
buildAllPlatforms syncronous

### ISSUE THREAD

**Issue by migumuno** [amzn/style-dictionary#234]
Hi!

Are there any way to know when buildAllPlatforms function ends? I need to compress all the files generated.

Thx!

**Comment by dbanksdesign** [comment]
If you are only generating files with the `files` array in the config (as opposed to generating files with an `action`), buildAllPlatforms is synchronous. So if you use style dictionary in a node file you can do this:

```javascript
const StyleDictionary = require('style-dictionary').extend('config.json');
// or however you like to declare your configuration

StyleDictionary.buildAllPlatforms();

console.log('Done!');
```

The only hiccup is if you create files with an action, and inside the action you use asynchronous methods like `fs.writeFile` instead of `fs.writeFileSync` those actions may or may not finish by the time `.buildAllPlatforms()` returns. Does that make sense?

**Comment by chazzmoney** [comment]
All of the actions that SD includes are synchronous as written. The case that Danny mentioned would only happen with custom actions created using registerAction. If you do this, you should be able to create your own method to detect those actions completing as well.

**Comment by chazzmoney** [comment]
Let us know if this answered your question or if you need more info.

Thanks!

**Comment by chazzmoney** [comment]
Closing as we have not heard back; feel free to reopen if you need more info.
