### ISSUE TITLE
Feature Request: Associations between Properties 

### ISSUE THREAD

**Issue by ryanfitzer** [amzn/style-dictionary#395]
I think a powerful feature to add would be the ability the associate one property with another. For example, associating a particular `font-size` with its respective `line-height`. (I realize this is currently possible, as I show at the end, but it's much more verbose.)

My initial approach would be the following:

**font/size.json**:
```json
{
    "font": {
        "size": {
            "xsmall": {
                "value": "0.75",
                "associations": [
                    "{font.line-height.xsmall}"
                ]
            }
        }
    }
}
```

**font/line-height.json**:
```json
{
    "font": {
        "line-height": {
            "xsmall": {
                "value": "1.25"
            }
        }
    }
}
```

**Result**:
```json
{
    "font": {
        "size": {
            "xsmall": {
                "value": "0.75",
                "associations": [
                    {
                        "line-height": {
                            "xsmall": {
                                "value": "1.25"
                            }
                        }
                    }
                ]
            }
        }
    }
}
```

Of course, this is currently possible using a more verbosity:

```json
{
    "font": {
        "size": {
            "xsmall": {
                "value": "0.75",
                "associations": [
                    {
                        "line-height": {
                            "xsmall": {
                                "value": "{font.line-height.xsmall.value}"
                            }
                        }
                    }
                ]
            }
        }
    }
}
```

Thoughts? Any recommendations for a better approach that would achieve the same result?

**Comment by dbanksdesign** [comment]
Are you trying to create a token group, for example a set of typographic styles (font-size, line-height, color, etc.)? What are you trying to accomplish with the association, like what is the end goal?

**Comment by ryanfitzer** [comment]
The end goal is to be able to access the `size.line-height.<item>` that is associated with `size.font.<item>` within a custom format, or custom build.

I'm building out a custom stylesheet using [Tailwind](https://tailwindcss.com/). This is done by using the json property files that are generated by Style Dictionary. The end result for this particular example would be each token available as an individual rule in the stylesheet, as well as coupled together into one rule:

```css
.line-height-small { line-height: 1.5rem; }
.font-size-small { font-size: .875rem; } 
.text-size-small {
  font-size: .875rem;
  line-height: 1.5rem;
}
```

Also, I'm not able to map it by item `small` -> `small` because there are more fonts sizes than there are line heights.

But this would also be useful if one was using a custom format.

**Comment by dbanksdesign** [comment]
I created a quick example repository for you: https://github.com/dbanksdesign/style-dictionary-assiciations-example

There are 2 directories: v1 and v2. v1 has what you put in your example and it works. v2 is a suggested change in structure. Both work, just a suggestion. 

Your first example code does work in Style Dictionary. The reason is Style Dictionary is "dumb" when it does reference/alias resolving. To Style Dictionary it sees one big object and whenever it comes across a string with `{}` it tries to replace that with whatever it finds at that object path. Alias/reference resolution happens after all transforms are applied so referencing the whole token, `{font.line-height.xsmall}` will give you the whole token object with other properties on it that Style Dictionary adds. 

A quick note on the example: the built-in transforms use a specific object structure for classifying tokens which does not match your example. It assumes a top-level namespace of "size" then a namespace under that of "font" to properly apply font-size transforms. This is not an issue if you create your own custom transforms.

**Comment by ryanfitzer** [comment]
Apologize for not responding sooner. I just tried the approach in V1 and it worked! While it's been a while, I know I'd tried something similar in  another situation and got an error when `.value` wasn't in the alias path. I guess I wrongly assumed from that experience that V1 wasn't possible. My bad :(

Thanks @dbanksdesign for the detailed response and example repo. And thanks @chazzmoney for following up. I'll close this issue.
