### ISSUE TITLE
Sketch Color Palette  V2 - Wrong HEX Values

### ISSUE THREAD

**Issue by mbulfair** [amzn/style-dictionary#407]
So I just noticed this, while visually looks correct, our project needs to output the correct hex values.

As a test I ran the following:

Starting with  `#0b7dbb`

Using ` "transforms": ["name/ti/camel", "attribute/cti", "color/sketch"],`

Results:
```json
      "red": "0.04",
      "green": "0.49",
      "blue": "0.73",
```

Import into sketch palettes, the hex value is wrong.

![Pasted Graphic](https://user-images.githubusercontent.com/5325543/77544313-3b1ed600-6e7f-11ea-8ba8-e1c06f8df1d8.png)

Used this online tool https://craigdallimore.github.io/sketch-palette-generator/?ref=thesketchapphub

Result:
```json
      "blue": "0.7333333333333333",
      "green": "0.49019607843137253",
      "red": "0.043137254901960784",
```
In Sketch:  This is correct value

![Pasted Graphic 1](https://user-images.githubusercontent.com/5325543/77544490-71f4ec00-6e7f-11ea-9ffe-ce1c7f6d721d.png)

Did I miss something or is there a bug?

**Comment by dbanksdesign** [comment]
It looks like there is a bug. It looks like it is because Style Dictionary is rounding the RGB values to 2 places which is not accurate enough for a hex value because each channel (R,G,B) is 0-255, whereas 2 decimal places only has the granularity of 0-100. 

Here is the offending code:
https://github.com/amzn/style-dictionary/blob/master/lib/common/transforms.js#L443

And here is a PR fixing it: #412

**Comment by mbulfair** [comment]
@dbanksdesign thank you for finding and fixing this, hope this get's released soon.
