### ISSUE TITLE
Question: how to represent tokens that have one value in platform A but multiple values in platform B

### ISSUE THREAD

**Issue by arielwb** [amzn/style-dictionary#455]
Hello!

I'm part of a team building a multi platform design system. He have implementations of components in iOS, Android, React and React Native, and we a currently using style dictionary to generate this multi platform tokens from a single source. YAY!

Now I have stumbled in a use case that I don't know how to handle yet.

I have some elevation tokens (shadows) that have specific properties and values for each platform.
Before I was overwriting properties following the multi theme/multi platform example, but in this case, this approach did not work, because Im not only changing values of properties, we have different properties between platforms.

some examples:

For React I want this output
```
"elevation": {
    "micro": "0 1px 1px 0 rgba(0, 0, 0, 0.14)",
  }
```

For iOS I want this output
```
var elevationMicroShadowColor = rgb(0, 0, 0, 0)
var elevationMicroShadowOffSetWidth = 0
var elevationMicroShadowOffSetHeight = -3
var elevationMicroShadowRadius = 3
var elevationMicroShadowOpacity = 0
```

For Android I want this output
```
var elevationMicro = 1
```

For React Native I want this output (Android + iOS)
```
"elevation": {
  "micro": {
    "shadowColor": "#000000",
    "shadowOffSet": {
      "width": 0,
      "height": -3
    },
    "shadowRadius": 3,
    "shadowOpacity": 0,
    "elevation": 1
  }
}
```

My first attempt was to write one default and overwrite the values by platform:

my "default" properties
```
{
  "elevation": {
    "micro": {
      "value": "0 1px 1px 0 rgba(0, 0, 0, 0.14)"
    }
}
```
my overwrite for iOS
```
{
  "elevation": {
    "micro": {
      "shadowColor": {
        "value": "nil"
      },
      "shadowOffSet": {
        "width": 0,
        "height": -3
      },
      "shadowRadius": {
        "value": 3
      },
      "shadowOpacity": {
        "value": 0
      }
    },
}
```

but it did not work, the ios properties are ignored and the "default" value is outputted to the ios file (I assume this is because of the data structure is not the same).

Is this something that we can achieve with style dictionary?
My first idea is to have all the properties on all platforms, but that is not so pretty :(

**Comment by dbanksdesign** [comment]
My apologies, I started researching this and writing up an example and got side-tracked. I wanted to build a complete example for you, but didn't finish so for now I'll just try to answer your questions the best I can. First, thank you for providing so much detail and context, it is super helpful to see what you want each platform to have so we can work backwards from that. 

The reason why it did not work as you expected is the way Style Dictionary works internally when it finds a design token. The way Style Dictionary knows what a design token is in nested object is any object that has a `value` attribute. Style Dictionary will walk down the object tree looking for something with a `value` and at that point it sees that it reached a token and it stops going deeper to find other tokens nested within it. So you can't have a token within a token, because that would mess with transforming them. Before any of that, Style Dictionary does a deep merge of all the token files it found based on your configuration. The way the multi-brand/multi-platform example works is that it will build a Style Dictionary multiple times passing in different sets of source files. Based on your example, doing a deep merge of those 2 JSON files will produce this:

```json
{
  "elevation": {
    "micro": {
      "value": "0 1px 1px 0 rgba(0, 0, 0, 0.14)",
      "shadowColor": {
        "value": "nil"
      },
      "shadowOffSet": {
        "width": 0,
        "height": -3
      },
      "shadowRadius": {
        "value": 3
      },
      "shadowOpacity": {
        "value": 0
      }
    }
}
```

Style Dictionary will get to `elevation.micro` and see it has a `value` attribute and think that whole object is a single token. 

There are a few potential solutions:

1. Don't include a default shadow token and only include platform-specific shadow tokens based on the platform being built. This will get around the issue of Style Dictionary thinking `elevation.micro` is a token itself.
2. Combine all parts of the shadow into a single object that is the token's value:

```json
{
  "shadow": {
    "micro": {
      "value": {
        "color": "#000000",
        "offsetWidth": 0,
        "offsetHeight": -3,
        "radius": 3,
        "opacity": 0.14,
        "elevation": 1
      }
    }
}
```

You would need to create custom transforms and formats to handle transforming this shadow type token. I think this is a great use-case that we should probably better support with the built-in transforms and formats in Style Dictionary though.

**Comment by dbanksdesign** [comment]
This is a similar question to #456

**Comment by jorenbroekema** [comment]
Closing, question considered as answered.
