### ISSUE TITLE
Key's containing letters and numbers become hyphenated

### ISSUE THREAD

**Issue by samwilliscreative** [amzn/style-dictionary#460]
I am trying to set up tokens for my typography, and have the following json:

```
"h1": {
   ...
}
```

However, when compiled, the token name becomes `h-1` rather than the intended `h1`. Is there a way around this?

**Comment by dbanksdesign** [comment]
Sorry that is unfortunately a known issue because we are using lodash's string methods and that is how those work. There are 2 other issues open about this: #449 and #300. I'll see if we can fix these issues in the next major release as this would be a breaking change to how the built-in name transforms currently work.

**Comment by samwilliscreative** [comment]
Sorry, didn't spot those other threads. Feel free to close this one in favour of the others!

**Comment by dbanksdesign** [comment]
Closing in favor of #449 and #300
