### ISSUE TITLE
Referencing using dot notation limits naming

### ISSUE THREAD

**Issue by lukasoppermann** [amzn/style-dictionary#468]
Hey,

due to using the dot notation only to reference values, the individual properties can not have names like `text-link` as a hyphen is not supported in do notation. 

Is this by design? And if so, what is the rational behind this decision? 

I am currently working on implementing referencing in a plugin and this means I need to convert names. However I am not sure it is great to convert something like `light blue` or `light-blue` to `lightblue` (there are more dramatic cases) as this detracts from the readability of the output.

**Comment by dbanksdesign** [comment]
While references do use dot notation, it isn't _really_ using dot notation. You can have names like `text-link` and reference them like `"{color.text-link.value}"` for instance just fine. Internally we split the reference string by the `.` character and then recursively walk down the object based on those keys. Keys that normally wouldn't be able to be referenced by dot notation in javascript, you actually can reference. You could even use spaces if you wanted. The only restriction then is you *can't* use dots in a name because that would mess with how it tries to find that reference. Here is the function that does that object walking: https://github.com/amzn/style-dictionary/blob/main/lib/utils/resolveObject.js#L146 

Name things however you want!

**Comment by lukasoppermann** [comment]
Ahh, okay, good to know.
