### ISSUE TITLE
How to Create A Deep Merged JSON File

### ISSUE THREAD

**Issue by danlevy1** [amzn/style-dictionary#489]
I want to output a single JSON file with all deep merged properties and resolved aliases. The `json/nested` format is great, but I can't seem to figure out which transform(s) to use. I'm thinking that I at least need the `attribute/cti` transform, but using that transform alone causes a token collision error (i.e. `While building <filename>, token collisions were found; output may be unexpected.`). If I add a second transform such as `name/cti/kebab` or `name/cti/constant`, the output is exactly as I would expect, but the output does not look any different if I use `name/cti/kebab` vs `name/cti/constant` along with `attribute/cti`. Is there a simpler approach, or is the build system just set up in a way where `name/cti/*` is just going to produce the same output when using the `json/nested` format?

**Comment by danlevy1** [comment]
What I find interesting is that, if my `transformGroup` is either `[]` or `[attribute/cti]` (without a `name/cti/*`), I get the above token collision error, but the output `JSON` file is correct (i.e. is is a deep merge with resolved aliases).

**Comment by dbanksdesign** [comment]
The token collision error happens when tokens have the same `name` when building a file. It does this by checking the `name` attribute on each token, which by default is set to the token's object key. This is helpful when building flat arrays of tokens like SCSS or CSS variables because you would get name collisions and have potentially breaking behavior. For formats that output an nested object structure it doesn't really matter because those collisions won't have any effect. 

The reason why using name transforms like `name/cti/kebab` have no effect is the same reason, name transforms change the `name` attribute on each token, but don't change the overall object structure of the entire dictionary. For nested object formats like `json/nested` name transforms have no effect. It would be a bit odd to have the output look like this:

```json
{
  "color": {
    "core": {
      "colorCoreRed": "#ff0000"
    }
  }
}
```

That is why for nested object formats name transforms don't have an effect, but also why adding any name transform will get rid of the collision warnings. We are working on having better log levels in the console as some find warnings like that irrelevant and messy. 

But if you use the `json/flat` format which outputs a flat object, the name transform would have an effect:

```json
{
  "colorCoreRed": "#ff0000"
}
```

Does that answer your question?

**Comment by danlevy1** [comment]
Yeah, and thanks for the explanation!
