### ISSUE TITLE
Create sketch plugin?

### ISSUE THREAD

**Issue by chazzmoney** [amzn/style-dictionary#5]
Create a sketch plugin that allows an export to a style-dictionary collection of JSON files.

**Comment by jarodtaylor** [comment]
I know you suggested this back in 2016, but was curious if it was on a roadmap. Would love to see how to integrate this into our Sketch/Zeplin workflow.

**Comment by dbanksdesign** [comment]
This is something we would love to have, but we haven't had time for it. We do have another library called [Sketch Constructor](https://amzn.github.io/sketch-constructor/#/) that allows you to read/write/manipulate Sketch files without using Sketch or Sketch plugins, and it hooks into Style Dictionary nicely. 

I'm curious to hear a bit more about your Sketch/Zeplin workflow, and what specifically you are looking for so that we can incorporate that into the future vision.
