### ISSUE TITLE
How would I use style-dictionary with a "platform-scale"

### ISSUE THREAD

**Issue by mrtnbroder** [amzn/style-dictionary#577]
I'm a big fan of [Adobes Design System](https://spectrum.adobe.com) in which they talk about "platform scales". Simply put, they have split their spacing, dimension etc. design tokens into two scales. Desktop and Mobile (for Web). More about that here: https://spectrum.adobe.com/page/platform-scale/

I really like this style and would love to do the same thing with style-dictionary. Would this be possible currently and if so, how?

When taking a look at this picture from style-dictionaries website:
![image](https://user-images.githubusercontent.com/1118826/112228740-11cf8c00-8c32-11eb-8670-9bc648f38105.png)

I would say that this platform-scale would actually be a new "type", right between `category` and `type` here on the picture. So I'm not sure how I would tackle this currently with style-dictionary. Hope that makes sense!

**Comment by chazzmoney** [comment]
Sorry for the slow response here - we were busy pushing 3.0 out the door. @dbanksdesign did you have thoughts on this? It is sensible and doable in our current form, but messes with the "nice" CTI features we include...

**Comment by dbanksdesign** [comment]
My bad! Having different scales for mobile and desktop, or really having just different values for any platform is possible. The best way to accomplish that is to follow the [multi-brand-multi-platform example](https://github.com/amzn/style-dictionary/tree/main/examples/advanced/multi-brand-multi-platform). At a high level what this is doing is running Style Dictionary multiple times with slightly different configurations where you swap out different token files based on the platform. Let me know if that makes sense!

**Comment by chazzmoney** [comment]
@mrtnbroder Did the response help? Do you have more questions?

**Comment by dbanksdesign** [comment]
Another thought that just came up was you could also use [`basePxFontSize`](https://github.com/amzn/style-dictionary/issues/663) on the platform configuration as a way to have different scales for different platforms. It is a bit blunt of a solution, but could work as well.

**Comment by chemoish** [comment]
@dbanksdesign thoughts on a direction or contribution that would provide benefit?

**Comment by dbanksdesign** [comment]
Apologies for the delay...

`basePxFontSize` is used in any transform that is `remTo*`, for example `size/remToPt` or `size/remToDp`. This allows you to scale font and padding sizes for native platforms. Originally, these transforms just assumed a multiplier of 16, where a font or padding of 1rem is roughly equivalent to 16 pt/dp/sp on native platforms. Using `basePxFontSize` you could scale up or down all your font size and padding values by a uniform amount. So if you wanted your sizes on Android and iOS to be little bit smaller, you could set it to 14, or a little bit bigger and set it to 18. It is a 'blunt' tool because it will affect all font and padding tokens for that platform configuration, which might not always be the right solution. 

Your example is basically doing what the transformer is already doing, but just with a different matcher function and name for where the multiplier is store (`scale` v. `basePxFontSize`). https://github.com/amzn/style-dictionary/blob/ad7f6ea555ec77defd264c9ade9628aefd108959/lib/common/transforms.js#L837

You could write it like this (if you changed scale to basePxFontSize in your config):

```javascript
module.exports = {
  matcher: (token) => typeof token.value === "string" && token.value.indexOf("px") !== -1,
  transformer: styleDictionary.transform["size/pxToRem"].transformer
};
```

In one of those PRs where we added basePxFontSize we had talked about adding a more generic transform that would work on any size rather than forcing all values to be rem or px units. I think that might be something you are looking for? A transform that would be `size/rem` and if it detects a value with 'px' it will divide the value by the scale or basePxFontSize and if it detects a rem value it will pass it through. I think that would be a good contribution if you'd like to try it.

**Comment by chemoish** [comment]
Thanks for the reply.

I totally miss understood the purpose of `size/pxToRem`. Since `remTo` and `pxTo` were using `basePxFontSize`, I incorrectly assumed they would work together somehow—they obviously don't since tokens need to be constructed differently. I still don't understand the purpose of `basePxFontSize` in `size/pxToRem`, but :shrug:.

In my use case I want to define all values by px (easier to author), scale all values up 25%, then transform into platform. So yea, I think I am looking for the generic transform. Whoops.

**Comment by jorenbroekema** [comment]
Closing question issue, considered as answered.

**Comment by mrtnbroder** [comment]
Sorry I forgot to tell I've found a solution. I created a transform and been using that. For anyone interested:

(I use YAML) You define your tokens and split them into "sets" ("medium" and "large" are platform scales):

```
global:
  border:
    width:
      "100":
        value: "1px"
      "200":
        value: "2px"
      "400":
        value: "4px"
    radius:
      "75":
        sets:
          medium:
            value: "2px"
          large:
            value: "2px"
      "100":
        sets:
          medium:
            value: "4px"
          large:
            value: "5px"
      "200":
        sets:
          medium:
            value: "8px"
          large:
            value: "10px"
```

sets transformer:

```
const _ = require("lodash")

module.exports = {
  type: "name",
  name: "name/sets",
  transformer: (token, options) => {
    let path = token.path
    if (token.path.includes("sets")) {
      path = _.filter(token.path, (x) => x !== token.name && x !== "sets")
    }

    return _.kebabCase([options.prefix].concat(path).join(" "))
  },
}
```

And using that like this:

```
const StyleDictionary = require("style-dictionary")
const yaml = require("yaml")

StyleDictionary.registerParser({
  pattern: /\.yaml$/,
  parse: ({ contents }) => yaml.parse(contents),
})

StyleDictionary.registerTransform(require("./transforms/name-sets.js"))

const things = [
  {
    type: "color",
    value: "light",
  },
  {
    type: "color",
    value: "dark",
  },
  {
    type: "scale",
    value: "large",
  },
  {
    type: "scale",
    value: "medium",
  },
]

const createConfig = (c) => {
  const source = [
    `src/${c.type}/globals/**/!(_*).yaml`,
    `src/${c.type}/aliases/**/!(_*).yaml`,
    `src/${c.type}/components/**/!(_*).yaml`,
  ]

  /** @type {import("style-dictionary").Config} */
  const config = {
    // source: ["test/*.yaml"],
    source,
    platforms: {
      [`web/${c.value}`]: {
        // transformGroup: "css",
        transforms: [
          "name/sets",
        ],
        buildPath: "dist/css/",
        files: [
          {
            destination: `${c.value}.css`,
            format: "css/sets",
            filter: (token) => {
              return (
                (token.path.includes("sets") && token.path.includes(c.value)) ||
                !token.path.includes("sets")
              )
            },
            options: {
              outputReferences: true,
              selector: `.polygon--${c.value}`,
              // selector: `.nomads--${theme}`,
            },
          },
        ],
      },
    },
  }

  return config
}

things.forEach((c) => {
  StyleDictionary.extend(createConfig(c)).buildAllPlatforms()
})
```
