### ISSUE TITLE
registerFilter: can't find filter

### ISSUE THREAD

**Issue by hmalaud** [amzn/style-dictionary#613]
Using the npm module, I'm am having some problems with the registerFilter function:

1. From this line in the doc "_If you want a custom build system using the npm module, you can specify a custom location for a configuration file or use a plain Javascript object_" I understand I should be able to do this `styleDictionary.extend({"source":...,"platforms": ...}).buildAllPlatforms();` but when doing so the config.json takes precedence and when deleting it I get the following message "Build failed; unable to find config file."

2. I get "Error: Can't find filter: filter-js" when trying to use the string version of the registerFilter within the config.json, like so:

```
config.json
{
  "source": ["properties/**/*.json", ".properties_json/**/*.json"],
  "platforms": {
    "scss": {
      "transformGroup": "scss",
      "buildPath": "../../assets/tokens/",
      "files": [{
        "destination": "_variables.scss",
        "format": "scss/variables",
        "filter": "**filter-js**"
      }]
    }
  }
}
```

```
build.js
  styleDictionary.registerFilter({
    name: '**filter-js**',
    matcher: (token) => {
      return token.attributes.catgory == 'color';
    },
  });

  const sd = styleDictionary.extend('./config.json');

  sd.buildAllPlatforms();
```

Am I doing something wrong?

Thanks!

**Comment by dbanksdesign** [comment]
Could you post a bit more of your code? What is the npm script you are using or what is the terminal command you are using to run this? I just tried running your code and it works fine to me. Although I think there is a misspelling of 'category' in your filter. 

What I think is happening is you are probably using an npm script to call the Style Dictionary CLI, like: `style-dictionary build`. If you want to use the npm module version you would need to run `node build.js` instead. I think that would solve your two issues. The reason is using the CLI it will look for a `config.json` file by default unless you pass it a `--config ` flag with a path to another config file. That is probably why it seems that your `config.json` file takes precedence, what is really happening is your `build.js` file is never run. That would also explain why it says it can't find the filter.

**Comment by hmalaud** [comment]
Indeed you are right! I was using a task to execute my custom build.js but also the CLI command, and both were using the same config.json, so the custom one was able to read the registerFilter function, and not the other. Thanks for your help!

PS: Would have been reaaally useful to be able to use arrays or filter functions directly in the json :)

**Comment by dbanksdesign** [comment]
Do you mean like writing the filter function code in JSON? That might be a bit risky because then Style Dictionary would need to `eval` that code. A pattern that I tend to do a lot now that might be helpful is to use a JS file as the config rather than a JSON file. If you write a node module that exports an object and you give that file path to the `--config` argument in the CLI you can define custom filters, formats, transforms, etc. inline. You can see an example of this in here:

https://github.com/amzn/style-dictionary/tree/main/examples/advanced/node-modules-as-config-and-properties

In the package.json file, there is a script that calls `style-dictionary build --config ./config.js`. The **config.js** file exports an object that is used as the configuration. This example shows a few ways to add custom transforms and formats (filters work the same way), either by using the `.register` methods or by adding a `transform` or `format` object in the config. The keys in that object become the names of those transforms or formats. Also, if you use a JS file as configuration you can provide the filter function inline as well. Here is a quick example showing both methods:

```javascript
module.exports = {
  filter: {
    myFilter: function (token) {
      return token.attributes.category === "color";
    }
  },
  source: ["tokens/**/*.json"],
  platforms: {
    css: {
      transformGroup: `css`,
      buildPath: `build/`,
      files: [
        {
          destination: `color.css`,
          format: `css/variables`,
          filter: `myFilter`
        },
        {
          destination: `size.css`,
          format: `css/variables`,
          filter: function (token) {
            return token.attributes.category === `size`;
          }
        }
      ]
    }
  }
};

```

I'm curious about what you mean by arrays. Would you like to pass an array of filters to be applied in order?

**Comment by hmalaud** [comment]
Ah yeah, that's a way to do it, thanks!

**Comment by chazzmoney** [comment]
@hmalaud I think @dbanksdesign answered your question, yes? Can I close this or did you have further questions?

**Comment by hmalaud** [comment]
It's ok thanks! @chazzmoney
