### ISSUE TITLE
Style Dictionary as API response (AWS Lambda)

### ISSUE THREAD

**Issue by luckywabbit** [amzn/style-dictionary#661]
I am attempting to use Style Dictionary in a project that will ultimately be served as a Lambda function on AWS.
Style Dictionary seems to write its final design tokens out to files at the end of the build.
Lambda's have no file system to write to.

I'm hoping to find a function within Style Dictionary that will take in an object as it's source (instead of a file as a source),  and return the final converted values as an object to be returned by the Lambda endpoint. (instead of writing out the final values as a file).

Is there such functionality within Style Dictionary?

**Comment by chazzmoney** [comment]
Hi! Sounds like a fun use case.

You can read and write files with lambda function, but only to the /tmp directory. You can also mount a [shared EFS drive](https://aws.amazon.com/blogs/aws/new-a-shared-file-system-for-your-lambda-functions/) to read and write to, or send files to s3 after writing.

Within SD, you can also write a [custom format](https://amzn.github.io/style-dictionary/#/formats?id=custom-formats) but instead of returning a string to write, you could perform transactions with other AWS services - or cache results to a local object (in memory).

With either approach, you should be able to read the results out and return them from the lambda after the SD process completes.

Hope this is helpful!

**Comment by luckywabbit** [comment]
Hi @chazzmoney ,
Thanks so much for the reply.
I'll give that approach a try!

**Comment by chazzmoney** [comment]
@luckywabbit How did it go? Any luck?

**Comment by luckywabbit** [comment]
@chazzmoney  The /temp directory approach worked on the testing server quite well. Thanks so much for the solution!
