### ISSUE TITLE
unable to install style-dictionary

### ISSUE THREAD

**Issue by krishnasravya07** [amzn/style-dictionary#758]
npm install -g style-dictionary . Unable to install the package throughing access denied error

**Comment by jorenbroekema** [comment]
Access denied errors on npm install are because your current user doesn't have write access to the folders in which npm wants to install the dependencies.

When installing NPM packages globally, you might need sudo/administrator access to the folders where the global npm modules live.

You could run it with administrator privileges (sudo, or run terminal as admin on windows), or go to the folders where you have limited access and change the ownership of those folders to your user so you no longer need admin privileges to install there.

I'd google the npm error if you want more info, the error is not related to this library.

**Comment by krishnasravya07** [comment]
Thank you for telling about sudo. My wrong didn't try with it.
Able to download and work on it.
