### ISSUE TITLE
Add Support for Xamarin Resource Dictionaries

### ISSUE THREAD

**Issue by lermanrafi** [amzn/style-dictionary#78]
You should add support for Xamarin Resource Dictionaries so that those of us who develop in Xamarin can utilize your wonderful tool.
Thanks

**Comment by chazzmoney** [comment]
Thanks for the suggestion Robert!

I don't know much about Xamarin, so I was doing some googling.  I think the best resource for us to be able to complete this issue is here:

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/resource-dictionaries

Do you build in Xamarin? Is this is all we need to be able to understand how to build the correct files?

Appreciate the help!

Thanks,

/Charles

**Comment by chazzmoney** [comment]
We aren't going to work on this for now and I don't want to leave this hanging, so closing. Feel free to re-open if you would like to submit a PR.
