### ISSUE TITLE
How to handle colors with transparency?

### ISSUE THREAD

**Issue by davixyz** [amzn/style-dictionary#79]
I've been trying to figure it out how to add a transparent variant of a color.
something like this:
```
{
  "color": {
    "base": {
      "transparent": { "value": "#DDFF3300"}
  }
}
```
Normally in CSS you would use the word `transparent` but I know that's not cross platform compatible, so I was thinking maybe of using the hex8 value in here, so a total transparent could be `#00000000`.
When I run this with
```
    scss: {
      transformGroup: 'scss',
      buildPath: 'build/',
      files: [{
        destination: 'scss/variables.scss',
        format: 'scss/variables',
      }],
```
I'm just getting the first 6 values due to this group only handling the transforms as hex. Is there a way to specify a custom transform at property level? or how would I go about this... searched a lot in the docs and I ended up a little bit more confused on how to handle this.

**Comment by davixyz** [comment]
I was able to do what I wanted like this:
https://gist.github.com/davixyz/9d5132397e751f21674a6b86a3257a18

But I think there must be a more elegant approach to this... is there a better way?

**Comment by dbanksdesign** [comment]
You can actually do this if you use the 'color/rgb' transform. It will automatically output `rgb(0,0,0)` or `rgba(0,0,0,0.5)` depending on if the original color has transparency. You can use 8bit hex, rgba/rgb string, or rgb(a) object in the style dictionary JSON. Does that make sense?

Maybe we should change the 'scss' transformGroup to use the 'color/rgb' transform instead of 'color/hex'.

**Comment by dbanksdesign** [comment]
Updated your gist: https://gist.github.com/dbanksdesign/a0cec31947d33efb9a81076cd89b53bc

**Comment by dbanksdesign** [comment]
Updated the gist, you can use `lib/common/transformGroups` which hold the included transformGroups, then you can append more transforms on it. 

Note, in the gist in the transform I'm using `prop.original.value` because the `color/hex` transform would have already run and turned the value into a normal hex. 

Maybe we should just add the transform in the updated gist and use it in the default 'scss' transformGroup?

**Comment by davixyz** [comment]
Interesting the good thing is that the library has the flexibility of doing the same thing in multiple ways; If this a use case it's not needed to support I think I could do it manually.

Closing this because I got good answers

**Comment by jkinley** [comment]
Hey there. I am using a default installation of 3.0 rc2. Is there no way to have transparent colors without using custom transforms?

**Comment by dbanksdesign** [comment]
You can have colors with transparency without custom transforms as long as you aren't trying aliasing/referencing a color and then trying to add transparency to it. For example these should work:

```jsonc
{
  "color": {
    "red": { "value": "#ff0000cc" },
    "green": { "value": { "h": 120, "s": 0.5, "l": 0.5, "a": 0.5 } },
    "blue": { "value": { "h": "{hue.blue}", "s": 0.5, "l": 0.5, "a": 0.5} }
  },
  "hue": {
    "blue": 200
  }
}
```

Does that help?

**Comment by jkinley** [comment]
@dbanksdesign Actually, what I was trying to achieve is complete transparency. So for example, a secondary button, with no background. I am eventually going to dive into customizations (once I get through a presentation Friday!) but for now just trying to define complete lack of color. Thanks!

**Comment by dbanksdesign** [comment]
OH! My bad I totally misunderstood. You could use either of these:

```json
    "clear": { "value": "transparent" },
    "otherClear": { "value": "#f000" },
```

Or really any color with 0 alpha channel. Style Dictionary uses tinycolor2 for color transforms at the moment, which understands CSS named colors like "transparent".

**Comment by jkinley** [comment]
@dbanksdesign No worries. Probably my bad question! Anyway, when I do what you suggest it transforms to `$color-base-clear: rgba(0, 0, 0, 0);`, but it is showing up as black in my app. Pretty sure is me doing something silly.

![image](https://user-images.githubusercontent.com/19417886/105259177-24e5b300-5b40-11eb-9e0f-d9de36dd85dd.png)

**Comment by dbanksdesign** [comment]
Hmm, `rgba(0,0,0,0)` is valid CSS and would be fully transparent. I just tried that code in a React + Sass app I have running for a side project and it works. Could you inspect that element and see if there is anything weird going on?

**Comment by jkinley** [comment]
@dbanksdesign Ah, I figured out the issue. For my demo, I am outputting variables.js for use in Styled Components. The transform for this results in #00000, while the Sass output is rgba(0,0,0,0);

```
// variables.js

export const ColorBackgroundButtonSecondaryDefault = "#000000";

// Sass

$color-background-button-secondary-default: rgba(0, 0, 0, 0);

```

**Comment by dbanksdesign** [comment]
OH! Ok I know what is going on now! You are using the [js](https://amzn.github.io/style-dictionary/#/transform_groups?id=js) transformGroup which uses the [color/hex](https://amzn.github.io/style-dictionary/#/transforms?id=colorhex) transform which always outputs a 6-digit hex, so that is why you are getting `#000000`. Quick fix would be to replace the `transformGroup` in your configuration with:

```javascript
"transforms": ["attribute/cti", "name/cti/pascal", "size/rem", "color/css"],
```

**Comment by jkinley** [comment]
@dbanksdesign Yeah, starting to figure out how to make customizations. Thanks for your help.
