### ISSUE TITLE
Specify alternative units (PX, REM, EM or Unitless)

### ISSUE THREAD

**Issue by michaeltrilford** [amzn/style-dictionary#91]
Is there a way to adjust the default value on variables, as a rem unit is currently rendered by default.

**Comment by dbanksdesign** [comment]
The units for values get set in [transforms](https://amzn.github.io/style-dictionary/#/transforms). I'm assuming you are using the [scss](https://amzn.github.io/style-dictionary/#/transform_groups?id=scss) or [less](https://amzn.github.io/style-dictionary/#/transform_groups?id=less) transformGroup which uses the [size/rem](https://amzn.github.io/style-dictionary/#/transforms?id=sizerem) transform. There are other built-in transforms you can use or you can write your own. For example, we don't have 'em' transforms, but you could write one yourself with [registerTransform](https://amzn.github.io/style-dictionary/#/api?id=registertransform):

```js
const StyleDictionary = require('style-dictionary');

StyleDictionary.registerTransform({
  name: 'size/em',
  type: 'value',
  matcher: function(prop) {
    // You can be more specific here if you only want 'em' units for font sizes    
    return prop.attributes.category === 'size';
  },
  transformer: function(prop) {
    // You can also modify the value here if you want to convert pixels to ems
    return parseFloat(prop.original.value) + 'em';
  }
});

//...
```

Does that help? If you post your code somewhere I can take a look as well.

**Comment by michaeltrilford** [comment]
Hey mate, thanks for the response. 

In terms of what we are trying to achieve is to have the ability to have:

» some tokens are displayed with rgba values (Shadow)
» the ability to have unit-less values for certain tokens, e.g line-height.

We're just trying to work out where to put that snippet from above. I'm running the MyStyleD and not sure where to put it.

**Comment by dbanksdesign** [comment]
Ah ok, so you are going through the [quick start guide](https://amzn.github.io/style-dictionary/#/quick_start?id=creating-a-new-project)?

If you just want rgb/a colors, in your config.json file change line 5 from
```
"transformGroup": "scss",
```
to
```
"transforms": ["attribute/cti", "name/cti/kebab", "time/seconds", "content/icon", "size/rem", "color/rgb"],
```

Although that will change all color tokens to be rgb, not just ones with transparency. If you want colors to be hex if they don't have transparency, and rgba if they do, you can write a custom transform for that. To extend the functionality of style dictionary with custom transforms, formats, and templates, you can write a javascript file to run in node, and then rather than calling 'style-dictionary build' in the command line, you just run your javascript file in node like `node build.js`. You'd also need to make your directory a node module by running `npm init` and follow the prompts, then add a dependency on style dictionary, `npm i -D style-dictionary`

Here is an example javascript file that defines a custom transform to either output a hex or rgba for colors depending on if they have transparency or not:

```js
// build.js
const StyleDictionary = require('style-dictionary').extend('config.json');
const Color = require('tinycolor2');

StyleDictionary.registerTransform({
  name: 'color/css',
  type: 'value',
  matcher: function(prop) {
    return prop.attributes.category === 'color';
  },
  transformer: function(prop) {
      var color = Color(prop.value);
      if (color.getAlpha() === 1) {
        return color.toHexString();
      } else {
        return color.toRgbString();
      }
  }
});

StyleDictionary.buildAllPlatforms();
```
And in your config.json file, change line 5 again to be
```
"transforms": ["attribute/cti", "name/cti/kebab", "time/seconds", "content/icon", "size/rem", "color/css"],
```

Then you would run `node build.js` 

For adding unit-less values like line-heights, you can create a create a new category of tokens called 'numbers'. In the properties folder, you can create a new folder in there called 'numbers' and in there make a file called 'line-height.json' (technically the folder and filename don't actually matter, but it keeps things organized). In that file you can define your line-heights:
```json
{
  "number": {
    "line-height": {
      "base": { "value": 1 },
      "large": { "value": 2 }
    }
  }
}
```

Does that help? Sorry if it is a bit technical

**Comment by informa** [comment]
Great write up @dbanksdesign , thank you. 

Are there going to be any sass maps, sass lists as pre-defined formats in the future?

**Comment by dbanksdesign** [comment]
Yes, I would love to include those in the default formats! If you want to submit a PR for those I can review them. Take a look at this PR for adding Less formats: https://github.com/amzn/style-dictionary/pull/76

**Comment by chazzmoney** [comment]
@michaeltrilford @informa Would love your feedback on what Danny wrote up and any challenges you had finding that info in the documentation.  I'm working on making the documentation more clear and would like your feedback.

Also, if you can provide examples of specific output you are hoping for, we can see about adding those transforms in for you.

**Comment by michaeltrilford** [comment]
@chazzmoney 

We will catch up on Tuesday (Monday for you) to have a discussion around what we thought went well, and what could potentially be improved. We will share something with you mid week.

Thanks,
Mike.

**Comment by chazzmoney** [comment]
@michaeltrilford 
Hi Michael! Wanted to see if you had come up with any more feedback for us - we want to make sure we can be as helpful as possible!
